# Bienvenidos al curso de introducción a R

## Antes de empezar

R es un lenguaje que podemos ejecutar en múltiples lugares. Su lugar natural sería el editor propio de R, que se instala con R.

Otra forma de ejecutar sentencias de R es a través de RStudio que intenta hacer más amigable el ejecutar código R

La última forma es la que estáis viendo: Un Notebook de Jupyter

### ¿Qué nos aporta Jupyter?

Jupyter nos aporta interactividad con los datos. Es decir, el cuaderno que estemos trabajando lo podemos modificar a nuestro gusto, cambiando valores para probar, etc. Tras esto podremos guardarlo y tendremos una copia personalizada.

### ¿Tengo que tener instalado Jupyter?

Esa es una opción, pero también podemos utilizar el proyecto de Google llamado Colaboratory, que nos permite cargar los ficheros jupyter online sin necesidad de guardar nada.

Para acceder a la web de colaboratory:

https://colab.research.google.com

Una vez allí, en la pantalla de bienvenida, copiaremos este repositorio creado para este curso:




## Comenzamos con R

#### Asignando un valor a una variable

Lo más básico que se puede hacer en R es asignar una variable, esto se puede hacer bien colocando el nombre de la variable y el signo <- y después el valor

In [1]:
miVariable <- 10

#### Imprimiendo una variable

Lo siguiente será lógicamente imprimir su valor, hay dos formas en R:
- De forma implícita: Es decir escribiendo en la línea de comando la variable, sin más
- De forma explícita: Con la función Print

In [2]:
miVariable

[1] 10

In [3]:
print(miVariable)

[1] 10


#### Comentarios

Los comentarios, necesarios cuando los códigos son muy grandes, en R se escriben colocando una almohadilla *#* al principio del texto.

Lo que va detrás no se ejecuta

In [4]:
# Esto es un comentario

#### Otras operaciones iniciales

También podemos hacer cálculos directos sobre las variables o sobre la línea de comandos:

In [5]:
miVariable <- miVariable*2
print(miVariable)

[1] 20


In [6]:
miVariable <- miVariable/4
print(miVariable)

[1] 5


## Tipos de datos en R

Todas las cosas que manipula R se llaman objetos. En general, éstos se construyen a partir de objetos más simples. De esta manera, se llega a los objetosmás simples que son de cinco clases a las que se denomina atómicas y que son las siguientes:

- numeric (números reales)
- integer (números enteros)
- complex (números complejos)
- character (cadenas de caracteres)
- logical (lógicos o booleanos, que sólo toman los valores True o False)


### Datos numéricos

Son los más importantes en un lenguaje como R tan vinculado con la estadística y el tratamiento de la información.

Como vemos en la lista anterior, hay tres tipos: numeric, integer y complex


In [7]:
x <- 2 # Se asigna el valor 2 a x
print(x) # Se imprime el valor de x

[1] 2


In [8]:
class(x) # Muestra cuál es la clase de x

[1] "numeric"

In [9]:
x <- 6/2 # Se asigna el valor de la operación dividir 6/2 a x
print(x)

[1] 3


In [10]:
class(x)

[1] "numeric"

A pesar de que no tenemos decimales, sigue diciendo que es un numeric, un valor real (doble, de coma flotante)
 
Para decirle implícitamente que el número es integer, se pone una L al final de la definición.

In [11]:
x <- 23L; print(x)

[1] 23


In [12]:
class(x)

[1] "integer"

Si queremos que el resultado de una operación acabe siendo de un tipo determinado, debemos englobarlo en un **as.**  seguido del tipo de dato que queramos:

In [13]:
x <- as.integer(6/2)
print(x)
class(x)

[1] 3


[1] "integer"

Por su parte, los números complejos, complex en el lenguaje, tienen una sintaxis muy particular; misma que se tiene que emplear para indicar explícitamente que un número introducido corresponde a ese tipo:

In [14]:
x <- 21 + 2i
y <- 2i + 21 # El mismo valor que x
z <- -1 + 0i # Corresponde a -1
tt <- sqrt(z) # raíz cuadrada de -1
print(x); print(y); print(z); print(tt)

[1] 21+2i
[1] 21+2i
[1] -1+0i
[1] 0+1i


In [15]:
class(tt)

[1] "complex"

También, existe un valor numérico especial, Inf, que  representa el infinito y que puede resultar en algunas expresiones, por ejemplo:

In [16]:
x <- 1/0 # División por cero
print(x)

[1] Inf


In [17]:
# Tambien dividir un número por Inf da cero:
y <- 1/Inf
print(y)

[1] 0


Finalmente, algunas operaciones pueden resultar en algo que no es un número, esto se representa por el valor NaN:

In [18]:
x <- 0/0
print(x)

[1] NaN


### Vectores

Pero estas clases atómicas, no se manejan de manera individual. En todos los ejemplos anteriores, R ha creado implícitamente un tipo de objeto llamado **VECTOR** y lo ha creado de longitud 1. Son esos vectores los que han sido asignados a nuestras variables (aunque no nos lo haya dicho)

In [19]:
x <- 2 # Se asigna el valor 2 a x
print(x) # Se imprime el valor de x

[1] 2


¿Cómo sabemos que es un vector?
Pues estuvo siempre delante de nuestros ojos:
El **[1]** que precede al valor, indica que se trata del primer elemento y único, en este caso, del vector que se muestra.

Hay diversas maneras de crear vectores de otras longitudes, que, como se ha dicho antes, son secuencias de objetos de la misma clase atómica.

La primer manera de crear vectores es a partir de los elementos individuales que compondrán el vector. Para esto se utiliza la función c()

In [20]:
c(4,2,-8) # Creación de un vector sin asignarlo a una variable

[1]  4  2 -8

In [21]:
## Distintas formas de asignar un vector a una variable
u <- c(4,2,-8) # Usando el operador <-

c(4, 2, -8) -> v # Usando el operador ->

# Usando la función assign:
assign("w", c(4, 2, -8))
# hay que tener cuidado con assign porque necesita que la variable se escriba entre comillas

p = c(4, 2, -8) # Usando el operador =

# Todo va a dar el mismo resultado
print(u); print(v); print(w); print(p)

[1]  4  2 -8
[1]  4  2 -8
[1]  4  2 -8
[1]  4  2 -8


#### Creando vectores a partir de datos de un fichero de texto

Supongamos que un fichero llamado Numeros.txt tenemos esto:

12 15.5 3.1
-2.2 0 0.0007

Pues si queremos crear un vector a partir de él:

In [24]:
vec <- scan("Numeros.txt")
print(vec)

[1] 12.0000 15.5000  3.1000 -2.2000  0.0000  0.0007


In [26]:
vec <- scan("Numeros.txt", integer())
print(vec); class(vec) # El vector y su clase

ERROR: Error in scan("Numeros.txt", integer()): scan() esperaba 'an integer', obtuvo '15.5'


Como se ve, debemos tener claro qué cargamos antes de asumirlo como un tipo de dato determinado.

Si ahora queremos hacer lo contrario, guardar un vector en un archivo:

In [27]:
vv <- c(5, 6.6, -7.7)
write(vv, "OtroArchivo.txt")

In [28]:
# Ahora recuperemos el contenido del archivo
v1 <- scan("OtroArchivo.txt")
print(v1)

[1]  5.0  6.6 -7.7


#### Creación de vectores a partir de secuencias y otros patrones

Un vector, inicializado en ceros, o FALSE, y de longitud determinada, se puede crear con la función vector(). Es esta misma función la que permite crear vectores sin elementos.

In [22]:
v <- vector("integer", 0)
print(v) # Un vector de enteros sin elementos

integer(0)


In [29]:
w <- vector("numeric", 3)
w # Un vector de tres ceros

[1] 0 0 0

In [30]:
u <- vector("logical", 5)
u # Un vector de 5 FALSE

[1] FALSE FALSE FALSE FALSE FALSE

El operador ’:’ permite generar un vector entero a partir de una secuencia creciente o decreciente de enteros, cuyos extremos se indican.

In [31]:
1:3

[1] 1 2 3

In [32]:
v <- 40:13
print(v); class(v) # El vector y su clase

 [1] 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16
[26] 15 14 13


[1] "integer"

In [34]:
# también pueden ser números no enteros
v <- pi:6
print(v); class(v) # El vector y su clase

[1] 3.141593 4.141593 5.141593


[1] "numeric"

Ha intentado crear una secuencia. 
Sin embargo, es el operador seq() el que permite generar una mayor variedad de secuencias numéricas.

In [36]:
v <- seq(from = 5, to = 15, by = 2)
print(v) # secuencia desde 5 hasta 15 de 2 en 2
class(v)

[1]  5  7  9 11 13 15


[1] "numeric"

In [37]:
v <- seq(from = 4, by = 2, length.out = 8)
print(v) # secuencia de 8 números iniciando desde 4 y de 2 en 2

[1]  4  6  8 10 12 14 16 18


Algunas veces es necesario repetir una secuencia de números varias veces para generar un vector deseado. La función rep() sirve para ese propósito.
Si, por ejemplo, quermos crear un vector con la repetición de la secuencia 4, 8, -3, cinco veces

In [38]:
v <- c(4, 8, -3)
w <- rep(v, times = 5)
print(w)

 [1]  4  8 -3  4  8 -3  4  8 -3  4  8 -3  4  8 -3


In [39]:
# si queremos unir dos vectores (concatenar)
u <- c(3, 4, 5)
v <- c(5, 4, 3)
w <- c(u, v)
print(w) # La concatenación de u y v

[1] 3 4 5 5 4 3


#### Acceder a los elementos de un vector
Dentro de un vector, sus elementos se pueden identificar mediante un índice entero, que en el caso de este lenguaje empieza con el 1.


In [40]:
v <- c(8, 7, -3, 2, 182)
v[5] # El quinto elemento

[1] 182

In [41]:
print(v[1]); print(v[3])

[1] 8
[1] -3


In [42]:
v[1] <- v[2] - v[5]
v # Note que el resultado de la operación se ha guardado en v[1]

[1] -175    7   -3    2  182

In [43]:
# el vector v tiene 5 elementos. 
# Si se asigna un valor al elemento 8, el vector crecerá hasta esa longitud
v[8] <- 213
v # v tiene ahora 8 elementos con espacios vacios: NA

[1] -175    7   -3    2  182   NA   NA  213

Otra característica interesante de este lenguaje, es que permite dar nombre y acceder por medio de ese nombre a los elementos individuales de un vector.
Supóngase por ejemplo que se tiene el registro de cantidades de ciertas frutas en un vector:

In [44]:
frutas <- c(15, 100, 2, 30)
frutas

[1]  15 100   2  30

In [47]:
# si queremos asociar esos valores con el nombre de la fruta
names(frutas) <- c("naranja", "pera", "manzana", "fresa")
print(frutas)

naranja    pera manzana   fresa 
     15     100       2      30 


In [49]:
# otra forma de hace lo mismo
frutas <- c(naranja = 15, pera = 100, manzana = 2, fresa = 30)
print(frutas)

naranja    pera manzana   fresa 
     15     100       2      30 


In [52]:
# Ahora, se la puede llamar por su nombre
frutas["manzana"] <- 8
frutas

# Almacenar valores con un nombres es un concepto informático que se llama diccionario
# o clave-valor

naranja    pera manzana   fresa 
     15     100       8      30

#### Operaciones sencillas con vectores

Todas las operaciones que podemos hacer con elementos simples, podemos hacerlas con vectores

In [53]:
v <- 2 + 3 # Resulta en un vector de longitud 1
print(v)
v <- c(2, 3) - c(5, 1) # Resulta en un vector de longitud 2
print(v)
v <- c(2, 3, 4) * c(2, 1, 3) # Resulta en un vector de longitud 3
print(v)
v <- c(2, 3, 4)^(3:1) # Eleva a potencias 3,2,1
print(v)

[1] 5
[1] -3  2
[1]  4  3 12
[1] 8 9 4


In [54]:
u <- 2:33
v <- c(4, 5, 6)
w <- c(u, v)
print(w)
length(w)

# la función length devuelve el número de elementos de un vector

 [1]  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
[26] 27 28 29 30 31 32 33  4  5  6


[1] 35

In [55]:
# ahora vamos a comprobar qué valores son menores o iguales que 10
w<=10

[1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE

In [56]:
v <- c(4, 5, 6, 7, 8, 9, 10) * c(1, 2)

Warning message in c(4, 5, 6, 7, 8, 9, 10) * c(1, 2):
"longitud de objeto mayor no es múltiplo de la longitud de uno menor"

In [57]:
v <- c(4, 5, 6, 7, 8, 9, 10) * c(1, 2, 1, 2, 1, 2, 1)
v

[1]  4 10  6 14  8 18 10

Si no queremos que nos muestre esos WARNINGS, porque a veces son más pesados que Seldon Cooper, pues:

In [59]:
options(warn = -1)
v <- c(4, 5, 6, 7, 8, 9, 10) * c(1, 2)
v

[1]  4 10  6 14  8 18 10

In [60]:
# Más operaciones vectoriales
v <- c(2, -3, 4)
w <- 2 * (v^2) # Dos veces el cuadrado de v
w

[1]  8 18 32

In [62]:
# Se desea la raíz cuadrada de los siguientes valores:
v <- c(9, 8, 31)
sqrt(v)

# El sin de 30, 45 y 60 grados: Primero se hace la conversión
# a radianes:
angulos <- c(30, 45, 60) * (pi/180)
angulos # En radianes

senos <- sin(angulos)
senos

[1] 3.000000 2.828427 5.567764

[1] 0.5235988 0.7853982 1.0471976

[1] 0.5000000 0.7071068 0.8660254

**Problema:
De un edificio, a una altura de 15 m, se ha lanzado con un ángulo de 50 grados, un proyectil a una velocidad de 7 m/s. ¿Cuáles serán las alturas (coordenadas y) del proyectil a cada 0.5 m de distancia horizontal desde donde se lanzó y hasta los 11 m?
Las ecuaciones que gobiernan este fenómeno son las siguientes:
x = v0x*t + x0
y = -1/2*gt^2 + v0y*t + y0**

Aquí, g es la aceleración de la gravedad, el parámetro t se refiere al tiempo,y la velocidad está descompuesta en sus componentes: v0x y v0y.

Ayuda: v0x y v0y se pueden calcular a partir de la velocidad inicial y el ángulo, usando las funciones trigonométricas sin() y cos(), y considerando que en R, los argumentos de esas funciones deben estar dados en radianes, y por tanto el ángulo debe convertirse a esa unidad.

In [63]:
# Definimos unos datos iniciales
g <- 9.81 # aceleración gravedad
x0 <- 0 # x inicial
y0 <- 15 # y inicial
vi <- 7 # velocidad inicial
alphaD <- 50 # ángulo-grados

# y para encontrar las componentes de la velocidad:
# Se convierte a radianes
alpha <- (pi/180) * alphaD # angulo-radianes
vox <- vi * cos(alpha) # componente x de velocidad inicial
vox

voy <- vi * sin(alpha) # componente y de velocidad inicial
voy

[1] 4.499513

[1] 5.362311

In [65]:
# ahora resolvemos el problema
# desde 0 hasta 11 de 0.5 en 0.5:
las.x <- seq(from = 0, to = 11, by = 0.5)

# que tenga un . o un _ en una definición de una variable
# lo único que le aporta es claridad.

In [68]:
# aplicamos las funciones
las.t <- (las.x - x0)/vox
las.y <- -(g/2) * las.t^2 + voy * las.t + y0
# Los resultados:
print('Las x')
las.x
print('Las y')
las.y

[1] "Las x"


[1]  0.0  0.5  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0
[16]  7.5  8.0  8.5  9.0  9.5 10.0 10.5 11.0

[1] "Las y"


[1] 15.0000000 15.5353081 15.9494790 16.2425125 16.4144087 16.4651675
 [7] 16.3947891 16.2032734 15.8906203 15.4568299 14.9019022 14.2258372
[13] 13.4286349 12.5102953 11.4708183 10.3102040  9.0284524  7.6255636
[19]  6.1015373  4.4563738  2.6900730  0.8026348 -1.2059407

### Matrices

Una matriz es un vector con un atributo adicional: dim. Para el caso de las matrices, este atributo es un vector entero de dos elementos, a saber: el número de filas y el número de columnas que componen a la matriz.

#### Construcción de matrices
Si lo hacemos a partir de un vector:

In [77]:
# supongamos que tenemos 
m <- 11:30 # Un vector con 20 números

In [78]:
# Para convertirla en matriz simplemente se especifica el
# atributo dim
dim(m) <- c(4, 5) # 4 filas y 5 columnas
m

[,1] [,2] [,3] [,4] [,5]
[1,] 11   15   19   23   27  
[2,] 12   16   20   24   28  
[3,] 13   17   21   25   29  
[4,] 14   18   22   26   30

In [79]:
class(m)

[1] "matrix"

In [80]:
# se puede cambiar en cualquier momento la dimensión
dim(m) <- c(5, 4) # ahora 5 renglones y 4 columnas
m

[,1] [,2] [,3] [,4]
[1,] 11   16   21   26  
[2,] 12   17   22   27  
[3,] 13   18   23   28  
[4,] 14   19   24   29  
[5,] 15   20   25   30

In [81]:
# para mostrar el valor de un elemento de la matriz
m[3, 2]
# y ahora con un solo índice, va bajando por columnas
m[8]

[1] 18

[1] 18

Una ventaja del lenguaje es que permite hacer referencia a una columna o a una fila de la matriz, como si se tratara de un sólo objeto, o sea como un vector. Para ello, se omite alguno de los dos índices en la expresión de acceso a la matriz, como se muestra más adelante. En el ejemplo que se viene examinando, esos vectores estarían compuestos por números enteros, aunque los
componentes de una matriz pueden ser también reales (numeric) o complejos (complex).

In [82]:
# El renglón 3 y la columna 2 de la matriz:
m[3, ]

[1] 13 18 23 28

In [83]:
m[, 2]

[1] 16 17 18 19 20

In [84]:
# La clase las columnas o renglones:
class(m[3, ])

[1] "integer"

Las matrices también se pueden crear de manera flexible por medio de la función primitiva matrix(), que permite alterar la secuencia por defecto de la creación de la matriz; esto es, ahora, si se quiere, se puede crear la matriz por filas en vez de columnas:

In [85]:
(m <- matrix(11:30, nrow = 5, ncol = 4, byrow = TRUE))

[,1] [,2] [,3] [,4]
[1,] 11   12   13   14  
[2,] 15   16   17   18  
[3,] 19   20   21   22  
[4,] 23   24   25   26  
[5,] 27   28   29   30

In [86]:
# además, a las filas y las columnas de una matriz se les pueden
# asignar nombres, que pueden ser después consultados o usados como índices:
rownames(m) <- c("uno", "dos", "tres", "cuatro", "cinco")
colnames(m) <- c("UNO", "DOS", "TRES", "CUATRO")

In [87]:
print(m)

       UNO DOS TRES CUATRO
uno     11  12   13     14
dos     15  16   17     18
tres    19  20   21     22
cuatro  23  24   25     26
cinco   27  28   29     30


In [88]:
# Consulta de los nombres de las columnas
colnames(m)

[1] "UNO"    "DOS"    "TRES"   "CUATRO"

In [89]:
# Una columna:
m[, "DOS"]

uno    dos   tres cuatro  cinco 
    12     16     20     24     28

Las funciones rbind() y cbind(), son otras que se pueden utilizar para construir matrices, dando, ya sea las filas  individuales o las columnas individuales, respectivamente.

In [90]:
m1 <- rbind(c(1.5, 3.2, -5.5), c(0, -1.1, 60))
m1

[,1] [,2] [,3]
[1,] 1.5   3.2 -5.5
[2,] 0.0  -1.1 60.0

In [91]:
class(m1[1, ]) # ahora compuesta de números reales

[1] "numeric"

In [92]:
(m2 <- cbind(c(1.5, 3.2, -5.5), c(0, -1.1, 60)))

[,1] [,2]
[1,]  1.5  0.0
[2,]  3.2 -1.1
[3,] -5.5 60.0

#### Acceso a los elementos individuales de una matriz
Para ello se emplea el operador **[ ]**. Supongamos que en la matriz m, del ejemplo anterior se quiere tener acceso al elemento que se encuentra en la fila 2 y en la columna 1 de la matriz


In [93]:
m[2, 1]

[1] 15

In [94]:
# Y también se pueden utilizar los nombres de fila y columna, si es que
# la matriz los tiene:
m["dos", "UNO"]

[1] 15

#### Operaciones sencillas con matrices
Todas las operaciones aritméticas válidas para vectores, son validas para las matrices, siempre y cuando, las matrices que se operan tengan las mismas dimensiones y se apliquen elemento a elemento, esto es, la operación se aplica entre cada columna, con su correspondiente, como si fueran vectores.

In [97]:
# definimos las matrices
(m <- matrix(1:15, nrow = 5, ncol = 3))

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8   13  
[4,] 4     9   14  
[5,] 5    10   15

In [98]:
(mm <- rbind(1:3, 3:1, c(1, 1, 1), c(2, 2, 2), c(3, 3, 3)))

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 3    2    1   
[3,] 1    1    1   
[4,] 2    2    2   
[5,] 3    3    3

In [99]:
# comenzamos a operar

m * mm

[,1] [,2] [,3]
[1,]  1   12   33  
[2,]  6   14   12  
[3,]  3    8   13  
[4,]  8   18   28  
[5,] 15   30   45

In [100]:
(A <- matrix(1:6, 3, 2))

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [101]:
(B <- rbind(7:9, 10:12))

[,1] [,2] [,3]
[1,]  7    8    9  
[2,] 10   11   12

Otra operación muy utilizada e implementada en R como una función, t(), es la traspuesta de una matriz. Esta es una operación en la que las filas se cambian a columnas y viceversa.

In [102]:
# Se usa la misma matriz A del ejemplo anterior:
A

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [103]:
t(A)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

## Factores y vectores de caracteres
Los caracteres, o más apropiadamente, las cadenas de caracteres, se utilizan para nombrar cosas u objetos del mundo. Igual que en el caso de los números, en R la clase character no se refiere a una cadena de caracteres aislada sino a un vector que contiene cero o más cadenas de caracteres. De este modo podríamos tener por ejemplo, una lista (o vector) con los nombres de personas, y otra,
paralela a la primera, con sus meses de nacimiento:

In [104]:
persona <- c("Hugo", "Paco", "Luis", "Petra", "Maria", "Fulano",
"Sutano", "Perengano", "Metano", "Etano", "Propano")
mes.nacimiento <- c("Dic", "Feb", "Oct", "Mar", "Feb", "Nov",
"Abr", "Dic", "Feb", "Oct", "Dic")
persona


[1] "Hugo"      "Paco"      "Luis"      "Petra"     "Maria"     "Fulano"   
 [7] "Sutano"    "Perengano" "Metano"    "Etano"     "Propano"

In [105]:
mes.nacimiento

[1] "Dic" "Feb" "Oct" "Mar" "Feb" "Nov" "Abr" "Dic" "Feb" "Oct" "Dic"

In [106]:
print(persona[7]); print(mes.nacimiento[7])

[1] "Sutano"
[1] "Abr"


In [107]:
print( c(persona[7], mes.nacimiento[7]) )

[1] "Sutano" "Abr"   


Los dos vectores anteriores pueden considerarse como una estructura de información,a la que se puede someter a algún tipo de procesamiento estadístico.

El lenguaje tiene muchas herramientas para ese propósito. Considérese, porejemplo, el problema de determinar la frecuencia de aparición de ciertos meses en el vector mes.nacimiento. En este caso, el lenguaje provee de una clase que facilita este tipo de análisis, a saber: la clase factor. Para entender esta clase, procedamos primeramente a transformar el vector mes.nacimiento a un
factor, mediante la función de conversión as.factor(), como sigue:

In [108]:
Fmes.nacimiento <- as.factor(mes.nacimiento)
Fmes.nacimiento

[1] Dic Feb Oct Mar Feb Nov Abr Dic Feb Oct Dic
Levels: Abr Dic Feb Mar Nov Oct

In [109]:
# y generamos la impresión ahora con el factor:
paste(persona[7], "nacio en el mes de", Fmes.nacimiento[7])

[1] "Sutano nacio en el mes de Abr"

Si se compara la impresión del factor Fmes.nacimiento con la del vector mes.nacimiento, se podría pensar que “no ha pasado mucho”. De hecho, la impresión bonita con la función paste(), ha resultado igual. Sin embargo, el
factor exhibe una estructura adicional denominada Levels, en la que se han registrado e identificado los elementos del vector sin repetición; esto es, los nombres únicos de los meses, en este caso. La estructura interna de esta clase se puede descubrir:

In [110]:
unclass(Fmes.nacimiento)

[1] 2 3 6 4 3 5 1 2 3 6 2
attr(,"levels")
[1] "Abr" "Dic" "Feb" "Mar" "Nov" "Oct"

La función table() toma típicamente como argumento un factor y regresa como resultado justamente la frecuencia de aparición de los niveles en el vector de índices

In [111]:
table(Fmes.nacimiento)

Fmes.nacimiento
Abr Dic Feb Mar Nov Oct 
  1   3   3   1   1   2 

In [112]:
meses <- c("Ene","Feb","Mar","Abr","May","Jun","Jul","Ago",
"Sep","Oct","Nov","Dic")
# Se incluyen meses que no están el el vector original
FFmes.nacimiento <- factor(mes.nacimiento, levels=meses)
FFmes.nacimiento

[1] Dic Feb Oct Mar Feb Nov Abr Dic Feb Oct Dic
Levels: Ene Feb Mar Abr May Jun Jul Ago Sep Oct Nov Dic

In [113]:
# Ahora la tabla de frecuencias es:
table(FFmes.nacimiento)

FFmes.nacimiento
Ene Feb Mar Abr May Jun Jul Ago Sep Oct Nov Dic 
  0   3   1   1   0   0   0   0   0   2   1   3 

#### Acceso a los elementos de un factor

In [114]:
# Un elemento individual del factor:
Fmes.nacimiento[10]

[1] Oct
Levels: Abr Dic Feb Mar Nov Oct

In [115]:
# Un elemento individual de los niveles:
levels(Fmes.nacimiento)[3]

[1] "Feb"

In [116]:
# Incluso es posible modificar todos o algunos de los niveles del factor. Por ejemplo:
levels(Fmes.nacimiento)[3] <- "febrero"
Fmes.nacimiento

[1] Dic     febrero Oct     Mar     febrero Nov     Abr     Dic     febrero
[10] Oct     Dic    
Levels: Abr Dic febrero Mar Nov Oct

Una lista, de la clase list, es una clase de datos que puede contener cero o más elementos, cada uno de los cuales puede ser de una clase distinta.

In [1]:
familia <- list("Maria", "Juan", 10, c("Hugo", "Petra"), c(8,
6))
familia

[[1]]
[1] "Maria"

[[2]]
[1] "Juan"

[[3]]
[1] 10

[[4]]
[1] "Hugo"  "Petra"

[[5]]
[1] 8 6

In [2]:
# los elementos de una lista pueden ser nombrados
familia <- list(madre="Maria", padre="Juan", casados=10,
hijos=c("Hugo", "Petra"), edades=c(8, 6))
familia

$madre
[1] "Maria"

$padre
[1] "Juan"

$casados
[1] 10

$hijos
[1] "Hugo"  "Petra"

$edades
[1] 8 6

#### Acceso a los elementos individuales de una lista
Al igual que en el caso de los vectores, las listas no serían de mucha utilidad sin la posibilidad de tener acceso a sus elementos individuales. El lenguaje,provee de este acceso mediante tres operadores, a saber: [ ], [[ ]], y $.

In [3]:
# Acceso de lectura
familia$madre

familia[["madre"]]

# Acceso de escritura
familia[["padre"]] <- "Juan Pedro"
familia$padre # para checar el nuevo valor

[1] "Maria"

[1] "Maria"

[1] "Juan Pedro"

In [4]:
familia$"madre" <- "Maria Candelaria"
mm <- "madre"
familia[[mm]]

familia[[ paste("ma", "dre", sep="") ]]

[1] "Maria Candelaria"

[1] "Maria Candelaria"

## Data Frames
Un data frame3 es una lista, cuyos componentes pueden ser vectores, matrices o factores, con la única salvedad de que las longitudes, o número de renglones, en el caso de matrices, deben coincidir en todos los componentes.
La apariencia de un data frame es la de una tabla y una forma de crearlos es mediante la función data.frame() .

In [5]:
(m <- cbind(ord=1:3, edad=c(30L, 26L, 9L)) )

ord edad
[1,] 1   30  
[2,] 2   26  
[3,] 3    9

In [6]:
(v <- c(1.80, 1.72, 1.05) )

[1] 1.80 1.72 1.05

In [7]:
ff <- data.frame(familia=c("Padre", "Madre", "Hijo"),
m, estatura=v)

In [9]:
mi.tabla <- read.table("Rtext.txt")
mi.tabla

Precio Piso Area Cuartos Edad Calentador
01 52.00  111   830 5       6.2  no        
02 54.75  128   710 5       7.5  no        
03 57.50  101  1000 5       4.2  no        
04 57.50  131   690 6       8.8  no        
05 59.75   93   900 5       1.9  si

In [10]:
colnames(mi.tabla)

[1] "Precio"     "Piso"       "Area"       "Cuartos"    "Edad"      
[6] "Calentador"

In [11]:
rownames(mi.tabla)

[1] "01" "02" "03" "04" "05"

In [12]:
mi.tabla$Piso

[1] 111 128 101 131  93

In [13]:
mi.tabla[[2]]

[1] 111 128 101 131  93

In [14]:
mi.tabla[2]

Piso
01 111 
02 128 
03 101 
04 131 
05  93

En el último caso, los datos se despliegan junto con el nombre de la columna y cada uno de los nombres de los renglones. Ello se debe a que en realidad, el operador [] extrae una rebanada del dato o variable sobre la cuál opera, un data frame en este caso, y que podríamos denominarlo como un sub-data frame aquí; esto es, se trata otra vez de un data frame pero más chiquito que el original

In [15]:
mi.tabla[3, 2]

[1] 101

In [16]:
# modificamos el elemento con:
mi.tabla[3, 2] <- 106
mi.tabla

Precio Piso Area Cuartos Edad Calentador
01 52.00  111   830 5       6.2  no        
02 54.75  128   710 5       7.5  no        
03 57.50  106  1000 5       4.2  no        
04 57.50  131   690 6       8.8  no        
05 59.75   93   900 5       1.9  si

Otra característica importante de los data frames es que, salvo que se indique otra cosa, las columnas de tipo character se convierten automáticamente a
tipo factor:

In [17]:
mi.tabla$Calentador

[1] no no no no si
Levels: no si

In [18]:
class(mi.tabla$Calentador)

[1] "factor"

In [19]:
mi.tabla$Total <- mi.tabla$Precio * mi.tabla$Area
mi.tabla

Precio Piso Area Cuartos Edad Calentador Total  
01 52.00  111   830 5       6.2  no         43160.0
02 54.75  128   710 5       7.5  no         38872.5
03 57.50  106  1000 5       4.2  no         57500.0
04 57.50  131   690 6       8.8  no         39675.0
05 59.75   93   900 5       1.9  si         53775.0

## Funciones en R
A diferencia de otros lenguajes de programación procedurales, como C, Java, y PHP, en R las funciones constituyen una clase. 

Por ejemplo, los objetos de esa clase pueden ser asignados a variables; podría darse el caso, incluso, de armar una lista cuyos elementos fueran funciones.
Aunque la escritura de funciones es parte de la programación que se verá más adelante, se indicará aquí la forma de crear funciones como una herramienta
para agrupar varias operaciones.
La sintaxis para la creación de una función es como sigue:


variable <- function(arg_1, arg_2, ..., arg_n) expresion

In [20]:
hipotenusa <- function(x, y) {
sqrt(x^2 + y^2)
}
class(hipotenusa)

[1] "function"

In [21]:
hipotenusa <- function(x, y) {
return(sqrt(x^2 + y^2))
}

In [22]:
# Para utilizar esta función lo hacemos con:
hipotenusa(3, 4)

[1] 5

In [23]:
hipotenusa(y = 4, x = 3)

[1] 5

Otra característica es que las funciones, en su definición, pueden tener valores asignados por defecto o en ausencia cuando es llamada la función:

In [24]:
hipotenusa <- function(x=3, y=4) { # valores por ausencia
return( sqrt( x^2 + y^2 ) )
}
# Llamamos a la función con argumentos "ausentes"
hipotenusa()

[1] 5

In [25]:
ff <- function(r) {
return(PI * r^2)
}

## Coerción
La coerción es obligar a un dato que sea de otro tipo:

In [26]:
x <- 1.03
x

y <- as.integer(x) # conversión a entero
y

z <- as.complex(y) # conversión a complejo
z

a <- c("1000", "2013.1", "0")
class(a)

b <- as.numeric(a) # conversión de character a otro tipo
b

class(b)

c <- as.logical(b) # conversión a lógico
# 0 es FALSE y distinto de 0 es TRUE
c
## [1] TRUE TRUE FALSE

[1] 1.03

[1] 1

[1] 1+0i

[1] "character"

[1] 1000.0 2013.1    0.0

[1] "numeric"

[1]  TRUE  TRUE FALSE

También, puede haber conversiones entre clases de datos más estructuradas.

Una inmediata es la conversión de una matriz a un data frame:

In [27]:
(m <- matrix(1:20, nrow = 5, ncol = 4))

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [28]:
ff <- as.data.frame(m)
ff

V1 V2 V3 V4
1 1   6 11 16
2 2   7 12 17
3 3   8 13 18
4 4   9 14 19
5 5  10 15 20